Update gh-set-secret.yml

diff --git a/.github/workflows/gh-set-secret.yml b/.github/workflows/gh-set-secret.yml
--- a/.github/workflows/gh-set-secret.yml
+++ b/.github/workflows/gh-set-secret.yml
@@ -45,24 +45,20 @@ jobs:
           org='${{ github.repository_owner }}'
 
           # Permissions: repo (all) and read:org
-          echo "Setting repository-wide secret..."
+          echo "Setting repository secret..."
           gh secret set "$repo_secret_name" --repo $repository \
             --body "$secret_body$repo_secret_name" || true
           echo "Done."
 
-          echo "Setting actions repository secret..."
+          # Permissions: repo (all) and read:org
+          echo "Setting repository actions secret..."
           gh secret set "$actions_secret_name" --repo $repository \
             --body "$secret_body$actions_secret_name" \
             --app actions || true
           echo "Done."
 
-          echo "Setting Codespaces repository secret..."
-          gh secret set "$codespaces_secret_name" --repo $repository \
-            --body "$secret_body$codespaces_secret_name" \
-            --app codespaces || true
-          echo "Done."
-
-          echo "Setting dependabot repository secret..."
+          # Permissions: repo (all) and read:org
+          echo "Setting repository dependabot secret..."
           gh secret set "$dependabot_secret_name" --repo $repository \
             --body "$secret_body$dependabot_secret_name" \
             --app dependabot || true
@@ -75,18 +71,25 @@ jobs:
             --body "$secret_body$deploymentEnvironment_secret_name" || true
           echo "Done."
 
+          # Permissions: repo (all), read:org, write:public_key
           echo "Setting organization secret..."
           gh secret set "$org_secret_name" --org $org \
             --body "$secret_body$org_secret_name" || true
           echo "Done."
 
-          echo "Setting user codespaces secret..."
+          # Permissions: repo (all), read:org, write:public_key
+          echo "Setting user secret..."
           gh secret set "$user_secret_name" --user \
             --body "$secret_body$user_secret_name" || true
           echo "Done."
 
-          echo "Sleeping 10s to wait for secrets propagate..."
-          sleep 10s
+          echo "Setting Codespaces secret..."
+          gh secret set "$codespaces_secret_name" --body "$secret_body$codespaces_secret_name" \
+            --app codespaces || true
+          echo "Done."
+
+          echo "Sleeping 5s to wait for secrets propagate..."
+          sleep 5s
           echo "Done."
 
   gh-test-secrets:
@@ -99,7 +102,6 @@ jobs:
       repo_secret: ${{ secrets.repo_secret }}
       actions_secret: ${{ secrets.actions_secret }}
       codespaces_secret: ${{ secrets.codespaces_secret }}
-      dependabot_secret: ${{ secrets.dependabot_secret }}
       org_secret: ${{ secrets.org_secret }}
       user_secret: ${{ secrets.user_secret }}
       deploymentEnvironment_secret: ${{ secrets.deploymentEnvironment_secret }}
@@ -107,10 +109,10 @@ jobs:
       - name: echo secrets
         shell: bash
         run: |
-          echo "repo_secret: $repo_secret"
-          echo "actions_secret: $actions_secret"
-          echo "codespaces_secret: $codespaces_secret"
-          echo "dependabot_secret: $dependabot_secret"
-          echo "org_secret: $org_secret"
-          echo "user_secret: $user_secret"
+          echo "Repository secret: $repo_secret"
+          echo "Repository actions secret: $actions_secret"
+          echo "Repository dependabot secret: Cannot be viewed from Actions"
+          echo "Organization secret: $org_secret"
+          echo "User secret: $user_secret"
+          echo "Codespaces secret: $codespaces_secret"
           echo "deploymentEnvironment_secret: $deploymentEnvironment_secret"
