Update gh-set-secret.yml

diff --git a/.github/workflows/gh-set-secret.yml b/.github/workflows/gh-set-secret.yml
--- a/.github/workflows/gh-set-secret.yml
+++ b/.github/workflows/gh-set-secret.yml
@@ -13,7 +13,6 @@ on:
 
 env:
   pat_token: ${{ secrets.PAT_TOKEN }}
-  pat_token_beta: ${{ secrets.PAT_TOKEN_BETA }}
   repo_secret_name: repo_secret
   actions_secret_name: actions_secret
   codespaces_secret_name: codespaces_secret
@@ -49,66 +48,62 @@ jobs:
           # Permissions: repo (all) and read:org
           echo "Setting repository actions secret..."
           gh secret set "$repo_secret_name" --repo $repository \
-            --body "$secret_body$repo_secret_name" || true
+            --body "$secret_body$repo_secret_name"
           echo "Done."
 
           # Permissions: repo (all) and read:org
           echo "Setting repository actions secret another way..."
           gh secret set "$actions_secret_name" --repo $repository \
             --body "$secret_body$actions_secret_name" \
-            --app actions || true
-          echo "Done."
-
-          # Permissions: repo (all) and read:org
-          echo "Setting repository dependabot secret..."
-          gh secret set "$dependabot_secret_name" --repo $repository \
-            --body "$secret_body$dependabot_secret_name" \
-            --app dependabot || true
+            --app actions
           echo "Done."
 
           # Permissions: repo (all) and read:org
           echo "Setting deployment environment secret..."
           gh secret set "$deploymentEnvironment_secret_name" --repo $repository \
             --env "$deployment_environment" \
-            --body "$secret_body$deploymentEnvironment_secret_name" || true
+            --body "$secret_body$deploymentEnvironment_secret_name"
+          echo "Done."
+
+          # Permissions: repo (all) and read:org
+          echo "Setting repository dependabot secret..."
+          gh secret set "$dependabot_secret_name" --repo $repository \
+            --body "$secret_body$dependabot_secret_name" \
+            --app dependabot
           echo "Done."
 
           # Permissions: repo (all), read:org, codespace:secrets
           echo "Setting user codespaces secret..."
           gh secret set "$user_secret_name" --user \
-            --body "$secret_body$user_secret_name" || true
+            --body "$secret_body$user_secret_name"
           echo "Done."
 
           # Permissions: repo (all), read:org, codespace:secrets
           echo "Setting user codespaces secret another way..."
           gh secret set "$codespaces_secret_name" --user  \
             --body "$secret_body$codespaces_secret_name" \
-            --app codespaces || true
+            --app codespaces
           echo "Done."
 
-          echo "Logging in with beta PAT token..."
-          gh auth logout --hostname github.com
-          gh auth login --with-token <<< $pat_token_beta
-
-          # Permissions: secrets:write
-          echo "Setting organization secret..."
+          # Permissions: repo (all), admin:org, admin:public_key
+          echo "Setting organization secret (only works in org repos, not user repos)..."
           gh secret set "$org_secret_name" --org $org \
             --body "$secret_body$org_secret_name" || true
           echo "Done."
 
           # This is not supported in version 2.6.0
-          # echo "Setting organization codespaces secret..."
-          # gh secret set "$codespaces_secret_name" --org $org  \
-          #   --body "$secret_body$codespaces_secret_name" \
-          #   --app codespaces || true
-          # echo "Done."
+          echo "Setting organization codespaces secret..."
+          gh secret set "$codespaces_secret_name" --org $org  \
+            --body "$secret_body$codespaces_secret_name" \
+            --app codespaces || true
+          echo "Done."
 
           # This is not supported in version 2.6.0
-          # echo "Setting repository codespaces secret..."
-          # gh secret set "$codespaces_secret_name" --repo $repository  \
-          #   --body "$secret_body$codespaces_secret_name" \
-          #   --app codespaces || true
-          # echo "Done."
+          echo "Setting repository codespaces secret..."
+          gh secret set "$codespaces_secret_name" --repo $repository  \
+            --body "$secret_body$codespaces_secret_name" \
+            --app codespaces || true
+          echo "Done."
 
           echo "Sleeping 5s to wait for secrets propagate..."
           sleep 5s
@@ -123,18 +118,16 @@ jobs:
     env:
       repo_secret: ${{ secrets.repo_secret }}
       actions_secret: ${{ secrets.actions_secret }}
-      codespaces_secret: ${{ secrets.codespaces_secret }}
-      org_secret: ${{ secrets.org_secret }}
-      user_secret: ${{ secrets.user_secret }}
       deploymentEnvironment_secret: ${{ secrets.deploymentEnvironment_secret }}
     steps:
       - name: echo secrets
         shell: bash
         run: |
-          echo "Repository secret: $repo_secret"
-          echo "Repository actions secret: $actions_secret"
-          echo "Repository dependabot secret: Cannot be viewed from Actions"
+          echo "Repository actions secret 1: $repo_secret"
+          echo "Repository actions secret 2: $actions_secret"
           echo "Deployment Environment secret: $deploymentEnvironment_secret"
-          echo "Organization secret: $org_secret"
-          echo "User secret: $user_secret"
-          echo "Organization codespaces secret: $codespaces_secret"
+          echo "Repository dependabot secret: Cannot be viewed from Actions"
+          echo "User codespaces secrets: Cannot be viewed from Actions"
+          echo "Organization secret: Only works if this is an org repo, not a user repo"
+          echo "Repository codespaces secret: Not supported as of version 2.6.0"
+          echo "Repository codespaces secret: Not supported as of version 2.6.0"
